// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBUyLfxCp4eKnwdbiXQY0Fdcb5YhrHH7eU',
    appId: '1:354658451800:android:5a351413597888fe7f652d',
    messagingSenderId: '354658451800',
    projectId: 'expense-flow-deda0',
    storageBucket: 'expense-flow-deda0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDZ_2JUxHLBMggdRdx_hy_M-zk3QnRUeIY',
    appId: '1:354658451800:ios:c6a012d6ccdb27947f652d',
    messagingSenderId: '354658451800',
    projectId: 'expense-flow-deda0',
    storageBucket: 'expense-flow-deda0.firebasestorage.app',
    androidClientId:
        '354658451800-qt68qooldiq0pjj9qt4enp2kof47kc7b.apps.googleusercontent.com',
    iosClientId:
        '354658451800-pear7cvbbafak5gk6j163t4kqci74o54.apps.googleusercontent.com',
    iosBundleId: 'com.nextgen.expenseflowapp',
  );
}
